// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/book_appointment.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/integrations/supabase/client.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
var SUPABASE_URL = "https://flucuclagrddzuaxkknt.supabase.co";
var SUPABASE_PUBLISHABLE_KEY = "sb_publishable_IqgKSngHvqStq_yivicI6g_7i7PUPxm";
function isNewSupabaseApiKey(value) {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}
function createSupabaseFetch(supabaseKey) {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : void 0
    );
    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }
    if (isNewSupabaseApiKey(supabaseKey) && headers.get("Authorization") === `Bearer ${supabaseKey}`) {
      headers.delete("Authorization");
    }
    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}
var supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY)
  },
  auth: {
    storage: typeof window !== "undefined" ? localStorage : void 0,
    persistSession: true,
    autoRefreshToken: true
  }
});

// src/lib/hospital/api.ts
var today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
var toDepartment = (r) => ({
  id: r.id,
  name: r.name,
  description: r.description ?? "",
  icon: r.icon ?? "Stethoscope",
  openFrom: r.open_from,
  openTo: r.open_to,
  rooms: r.rooms,
  load: r.load
});
var toDoctor = (r) => ({
  id: r.id,
  name: r.name,
  departmentId: r.department_id,
  specialization: r.specialization ?? "",
  qualification: r.qualification ?? "",
  experienceYears: r.experience_years,
  rating: Number(r.rating),
  fee: r.fee,
  room: r.room ?? "",
  available: r.available,
  days: r.days ?? [],
  slotStart: r.slot_start,
  slotEnd: r.slot_end,
  avgConsultMinutes: r.avg_consult_minutes
});
var toAppointment = (r) => ({
  id: r.id,
  tokenNumber: r.token_number,
  patientId: r.patient_id,
  patientName: r.patient_name,
  doctorId: r.doctor_id,
  departmentId: r.department_id,
  date: r.date,
  slot: r.slot,
  reason: r.reason ?? "",
  status: r.status,
  priority: r.priority,
  predictedWait: r.predicted_wait,
  createdAt: r.created_at
});
var toEmergency = (r) => ({
  id: r.id,
  patientName: r.patient_name,
  age: r.age ?? 0,
  condition: r.condition ?? "",
  triage: r.triage,
  arrivedAt: r.arrived_at,
  departmentId: r.department_id,
  assignedDoctorId: r.assigned_doctor_id ?? void 0,
  status: r.status
});
async function listDepartments() {
  const { data, error } = await supabase.from("hospital_departments").select("*").order("name");
  if (error) throw error;
  return (data ?? []).map(toDepartment);
}
async function listDoctors(filters) {
  let q = supabase.from("hospital_doctors").select("*").order("name");
  if (filters?.departmentId) q = q.eq("department_id", filters.departmentId);
  if (filters?.availableOnly) q = q.eq("available", true);
  const { data, error } = await q;
  if (error) throw error;
  let doctors = (data ?? []).map(toDoctor);
  const query = filters?.query?.trim().toLowerCase();
  if (query) {
    doctors = doctors.filter((d) => `${d.name} ${d.specialization}`.toLowerCase().includes(query));
  }
  return doctors;
}
async function listEmergencies() {
  const { data, error } = await supabase.from("hospital_emergencies").select("*").order("arrived_at", { ascending: false });
  if (error) throw error;
  return (data ?? []).map(toEmergency);
}
async function getDoctorQueue(doctorId) {
  const [{ data: doctorRow }, { data: aptRows, error }] = await Promise.all([
    supabase.from("hospital_doctors").select("avg_consult_minutes").eq("id", doctorId).maybeSingle(),
    supabase.from("hospital_appointments").select("*").eq("doctor_id", doctorId).eq("date", today).not("status", "in", '("cancelled","completed")').order("token_number")
  ]);
  if (error) throw error;
  const consult = doctorRow?.avg_consult_minutes ?? 10;
  const rank = { emergency: 0, high: 1, normal: 2 };
  const queue = (aptRows ?? []).map(toAppointment).sort((a, b) => rank[a.priority] - rank[b.priority] || a.tokenNumber - b.tokenNumber);
  return queue.map((appointment, i) => ({
    appointment,
    position: i + 1,
    etaMinutes: appointment.status === "in-consultation" ? 0 : i * consult
  }));
}
async function bookAppointment(input) {
  const { data: doctorRow, error: doctorErr } = await supabase.from("hospital_doctors").select("id, department_id, avg_consult_minutes").eq("id", input.doctorId).maybeSingle();
  if (doctorErr) throw doctorErr;
  if (!doctorRow) throw new Error("Doctor not found");
  const { data: sameDay, error: sameDayErr } = await supabase.from("hospital_appointments").select("token_number, status").eq("doctor_id", input.doctorId).eq("date", input.date);
  if (sameDayErr) throw sameDayErr;
  const tokenNumber = sameDay?.length ? Math.max(...sameDay.map((a) => a.token_number)) + 1 : 1;
  const waitingAhead = (sameDay ?? []).filter((a) => a.status === "waiting").length;
  const { data, error } = await supabase.from("hospital_appointments").insert({
    token_number: tokenNumber,
    patient_id: input.patientId,
    patient_name: input.patientName,
    doctor_id: doctorRow.id,
    department_id: doctorRow.department_id,
    date: input.date,
    slot: input.slot,
    reason: input.reason,
    status: "waiting",
    priority: input.priority ?? "normal",
    predicted_wait: Math.max(5, waitingAhead * doctorRow.avg_consult_minutes)
  }).select("*").single();
  if (error) throw error;
  return toAppointment(data);
}
async function getHospitalStats() {
  const [{ data: todays, error: aptErr }, { data: emergencies, error: emErr }, { data: doctors, error: docErr }, { data: departments, error: depErr }] = await Promise.all([
    supabase.from("hospital_appointments").select("status, predicted_wait").eq("date", today),
    supabase.from("hospital_emergencies").select("status"),
    supabase.from("hospital_doctors").select("available"),
    supabase.from("hospital_departments").select("id")
  ]);
  if (aptErr) throw aptErr;
  if (emErr) throw emErr;
  if (docErr) throw docErr;
  if (depErr) throw depErr;
  const rows = todays ?? [];
  const waiting = rows.filter((a) => a.status === "waiting");
  return {
    appointmentsToday: rows.length,
    waiting: waiting.length,
    inConsultation: rows.filter((a) => a.status === "in-consultation").length,
    completed: rows.filter((a) => a.status === "completed").length,
    activeEmergencies: (emergencies ?? []).filter((e) => e.status !== "stabilised").length,
    doctorsOnDuty: (doctors ?? []).filter((d) => d.available).length,
    totalDoctors: (doctors ?? []).length,
    departments: (departments ?? []).length,
    avgWait: Math.round(
      waiting.reduce((s, a) => s + (a.predicted_wait ?? 0), 0) / Math.max(1, waiting.length)
    )
  };
}

// src/lib/mcp/tools/book_appointment.ts
var book_appointment_default = defineTool({
  name: "book_appointment",
  title: "Book appointment",
  description: "Book a new OPD appointment for a patient with a specific doctor, date, and time slot.",
  inputSchema: {
    patientId: z.string().min(1).describe("Registered patient ID."),
    patientName: z.string().min(1).describe("Patient display name."),
    doctorId: z.string().min(1).describe("Doctor ID to book with."),
    date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Appointment date in YYYY-MM-DD format."),
    slot: z.string().regex(/^\d{2}:\d{2}$/).describe("Appointment time slot in HH:mm format."),
    reason: z.string().min(1).describe("Reason for the visit / symptoms."),
    priority: z.enum(["normal", "high", "emergency"]).optional().describe("Optional triage priority.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ patientId, patientName, doctorId, date, slot, reason, priority }) => {
    try {
      const appointment = await bookAppointment({
        patientId,
        patientName,
        doctorId,
        date,
        slot,
        reason,
        priority: priority ?? "normal"
      });
      return {
        content: [{ type: "text", text: JSON.stringify(appointment, null, 2) }],
        structuredContent: { appointment }
      };
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      throw new ToolError(message);
    }
  }
});

// src/lib/mcp/tools/get_doctor_queue.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_doctor_queue_default = defineTool2({
  name: "get_doctor_queue",
  title: "Get doctor queue",
  description: "Return the live OPD queue for a specific doctor, including patient positions and estimated waiting times.",
  inputSchema: {
    doctorId: z2.string().min(1).describe("The doctor ID to fetch the queue for.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ doctorId }) => {
    const queue = await getDoctorQueue(doctorId);
    return {
      content: [{ type: "text", text: JSON.stringify(queue, null, 2) }],
      structuredContent: { queue }
    };
  }
});

// src/lib/mcp/tools/get_hospital_stats.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_hospital_stats_default = defineTool3({
  name: "get_hospital_stats",
  title: "Get hospital stats",
  description: "Return a high-level snapshot of today's hospital operations: appointments, queue length, emergency load, and bed occupancy.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const stats = await getHospitalStats();
    return {
      content: [{ type: "text", text: JSON.stringify(stats, null, 2) }],
      structuredContent: { stats }
    };
  }
});

// src/lib/mcp/tools/list_departments.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_departments_default = defineTool4({
  name: "list_departments",
  title: "List departments",
  description: "List all hospital departments, including their operating hours, rooms, and current OPD load.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const departments = await listDepartments();
    return {
      content: [{ type: "text", text: JSON.stringify(departments, null, 2) }],
      structuredContent: { departments }
    };
  }
});

// src/lib/mcp/tools/list_doctors.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_doctors_default = defineTool5({
  name: "list_doctors",
  title: "List doctors",
  description: "Search and filter doctors by name, specialization, department, and availability.",
  inputSchema: {
    query: z3.string().optional().describe("Optional text search across name, specialization, and department."),
    departmentId: z3.string().optional().describe("Filter by department ID."),
    availableOnly: z3.boolean().optional().describe("Only return currently available doctors.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, departmentId, availableOnly }) => {
    const doctors = await listDoctors({ query, departmentId, availableOnly });
    return {
      content: [{ type: "text", text: JSON.stringify(doctors, null, 2) }],
      structuredContent: { doctors }
    };
  }
});

// src/lib/mcp/tools/list_emergencies.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_emergencies_default = defineTool6({
  name: "list_emergencies",
  title: "List emergency cases",
  description: "Return the current emergency triage board with red, yellow, and green cases and their status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const emergencies = await listEmergencies();
    return {
      content: [{ type: "text", text: JSON.stringify(emergencies, null, 2) }],
      structuredContent: { emergencies }
    };
  }
});

// src/lib/mcp/tools/predict_waiting_time.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";

// src/lib/hospital/ai.ts
function predictWaitingTime(queue, appointmentId, doctor) {
  const consult = doctor?.avgConsultMinutes ?? 10;
  const entry = queue.find((q) => q.appointment.id === appointmentId);
  const ahead = entry ? entry.position - 1 : queue.length;
  const emergencyLoad = queue.filter((q) => q.appointment.priority === "emergency").length * 6;
  const value = Math.max(0, Math.round(ahead * consult * 1.1 + emergencyLoad));
  return {
    value,
    confidence: ahead <= 3 ? 0.92 : 0.78,
    factors: [
      `${ahead} patient(s) ahead in queue`,
      `Avg consultation ${consult} min for this doctor`,
      emergencyLoad ? `+${emergencyLoad} min for emergency interruptions` : "No emergency interruptions expected"
    ],
    model: "wait-time-regressor-v1"
  };
}

// src/lib/mcp/tools/predict_waiting_time.ts
var predict_waiting_time_default = defineTool7({
  name: "predict_waiting_time",
  title: "Predict waiting time",
  description: "Predict the remaining waiting time for a patient in a doctor's OPD queue using the AI waiting-time model.",
  inputSchema: {
    doctorId: z4.string().min(1).describe("Doctor ID whose queue the patient is in."),
    appointmentId: z4.string().min(1).describe("Appointment ID of the patient.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ doctorId, appointmentId }) => {
    const [queue, doctors] = await Promise.all([getDoctorQueue(doctorId), listDoctors()]);
    const doctor = doctors.find((d) => d.id === doctorId);
    const prediction = predictWaitingTime(queue, appointmentId, doctor);
    return {
      content: [{ type: "text", text: JSON.stringify(prediction, null, 2) }],
      structuredContent: { prediction }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "remix-of-event-registration-page-template",
  title: "Remix of Event Registration Page Template",
  version: "0.1.0",
  instructions: "Tools for the AI-Based Smart Hospital Management System demo. Use these to query hospital departments, doctors, live queues, emergency cases, and hospital stats, or to book appointments and get AI waiting-time predictions. All data is synthetic demo data for the Smart India Hackathon project.",
  tools: [
    list_departments_default,
    list_doctors_default,
    get_hospital_stats_default,
    list_emergencies_default,
    get_doctor_queue_default,
    predict_waiting_time_default,
    book_appointment_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
